FileVersion = 1

[Project]
Name = "pcre2-beef"
DefaultNamespace = "pcre2"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\pcre2-8d.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\x64\\pcre2-8.lib"]
